package de.tum.pssif.xmi;

public enum XmiIoMapperTypes {
	CLASS, OPERATION, ATTRIBUTE, GENERALIZES, ASSOCIATION, PARAMATER, ACTOR, USECASE, COMPONENT, INCLUDES, INTERFACE, INTERFACE_REALIZATION, INVOCES, SUPPORTS, EXTENDS, DECISION_OPERATOR, MERGE_OPERATOR, FORK_OPERATOR, JOIN_OPERATOR, ACTION, BUFFER, OBJECT_FLOW, CONTROL_FLOW
}
