package org.pssif.consistencyLogic;

public enum MatchingMethods {

	EXACT_STRING_MATCHING,
	DEPTH_MATCHING,
	STRING_EDIT_DISTANCE_MATCHING,
	HYPHEN_MATCHING,
	LINGUISTIC_MATCHING,
	VECTOR_SPACE_MODEL_MATCHING,
	LATENT_SEMANTIC_INDEXING_MATCHING,
	CONTEXT_MATCHING;
	
}
